name: Image Size Guard
on:
  pull_request:
    paths:
      - "assets/**.png"
      - "assets/**.jpg"
      - "assets/**.svg"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enforce image size limits
        run: |
          LIMIT=$((300 * 1024)) # 300KB
          fail=0
          while IFS= read -r -d '' f; do
            sz=$(stat -c%s "$f" || stat -f%z "$f")
            if [ "$sz" -gt "$LIMIT" ]; then
              echo "❌ $f is too large: $sz bytes"
              fail=1
            fi
          done < <(find assets -type f \( -iname '*.png' -o -iname '*.jpg' -o -iname '*.svg' \) -print0)
          exit $fail
