name: Link Check (README)
on:
  workflow_dispatch:
  schedule:
    - cron: "19 3 * * 1,4"  # مرتين بالأسبوع

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run lychee
        uses: lycheeverse/lychee-action@v1
        with:
          args: >
            --no-progress
            --require-https
            --timeout 20
            --max-concurrency 8
            README.md
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
