name: Generate Snake
on:
  schedule:
    - cron: "21 2 * * *"  # يوميًا 02:21 UTC
  workflow_dispatch:

permissions:
  contents: write  # مهم جداً للسماح بالدفع إلى فرع output

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: akrmcodes
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark
      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
